// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbunpeIbLiHoKBg9OEAPLoKV9Soy72KKo',
    appId: '1:442397039597:web:54e5eca45ef4b79352e5e4',
    messagingSenderId: '442397039597',
    projectId: 'pinball-36d1a',
    authDomain: 'pinball-36d1a.firebaseapp.com',
    databaseURL: 'https://pinball-36d1a-default-rtdb.firebaseio.com',
    storageBucket: 'pinball-36d1a.appspot.com',
    measurementId: 'G-T5YGX7RPPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_KXU9w9h_FggkoRZfxRpGLzLKm3_onss',
    appId: '1:442397039597:android:1a532a44110d4c2152e5e4',
    messagingSenderId: '442397039597',
    projectId: 'pinball-36d1a',
    databaseURL: 'https://pinball-36d1a-default-rtdb.firebaseio.com',
    storageBucket: 'pinball-36d1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0KPlJeOT2f5aPmlhsUK68IZNMiyXw4uY',
    appId: '1:442397039597:ios:873ba5e9dcc5f8c252e5e4',
    messagingSenderId: '442397039597',
    projectId: 'pinball-36d1a',
    databaseURL: 'https://pinball-36d1a-default-rtdb.firebaseio.com',
    storageBucket: 'pinball-36d1a.appspot.com',
    iosBundleId: 'com.example.pinball',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0KPlJeOT2f5aPmlhsUK68IZNMiyXw4uY',
    appId: '1:442397039597:ios:b7dee3db0d300eb852e5e4',
    messagingSenderId: '442397039597',
    projectId: 'pinball-36d1a',
    databaseURL: 'https://pinball-36d1a-default-rtdb.firebaseio.com',
    storageBucket: 'pinball-36d1a.appspot.com',
    iosBundleId: 'com.example.pinball.RunnerTests',
  );
}
